name: Tag GitHub release

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Run npx semantic-release & create Github Release,
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ env.GH_PAT }}

