name: Tag GitHub release
on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'yarn'

      - name: Install foo dependencies
        run: yarn install
        working-directory: packages/foo

      - name: Install bar dependencies
        run: yarn install
        working-directory: packages/bar

      - name: Run semantic-release on foo,
        run: npx semantic-release -e semantic-release-monorepo
        working-directory: packages/foo
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

      - name: Run semantic-release on bar,
        run: npx semantic-release -e semantic-release-monorepo
        working-directory: packages/bar
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
